import type { ItemProperties, ItemType } from "../types";

export const ITEM_REGISTRY: Record<ItemType, ItemProperties> = {
  // Resources
  wood: {
    type: "wood",
    category: "resource",
    label: "Wood",
    stackSize: 75,
    baseValue: 1,
    weight: 1.0,
    flammability: 1.0,
    nutrition: 0,
  },
  stone: {
    type: "stone",
    category: "resource",
    label: "Stone",
    stackSize: 75,
    baseValue: 1,
    weight: 1.5,
    flammability: 0,
    nutrition: 0,
  },
  iron: {
    type: "iron",
    category: "resource",
    label: "Iron",
    stackSize: 75,
    baseValue: 3,
    weight: 1.2,
    flammability: 0,
    nutrition: 0,
  },
  gold: {
    type: "gold",
    category: "resource",
    label: "Gold",
    stackSize: 75,
    baseValue: 10,
    weight: 1.5,
    flammability: 0,
    nutrition: 0,
  },
  silver: {
    type: "silver",
    category: "resource",
    label: "Silver",
    stackSize: 75,
    baseValue: 5,
    weight: 1.3,
    flammability: 0,
    nutrition: 0,
  },
  coal: {
    type: "coal",
    category: "resource",
    label: "Coal",
    stackSize: 75,
    baseValue: 2,
    weight: 0.8,
    flammability: 1.0,
    nutrition: 0,
  },
  cloth: {
    type: "cloth",
    category: "resource",
    label: "Cloth",
    stackSize: 75,
    baseValue: 2,
    weight: 0.3,
    flammability: 0.8,
    nutrition: 0,
  },
  leather: {
    type: "leather",
    category: "resource",
    label: "Leather",
    stackSize: 75,
    baseValue: 2,
    weight: 0.4,
    flammability: 0.5,
    nutrition: 0,
  },

  // Food
  meat: {
    type: "meat",
    category: "food",
    label: "Raw Meat",
    stackSize: 50,
    baseValue: 2,
    weight: 0.5,
    flammability: 0,
    nutrition: 0.3,
  },
  berries: {
    type: "berries",
    category: "food",
    label: "Berries",
    stackSize: 50,
    baseValue: 1,
    weight: 0.1,
    flammability: 0,
    nutrition: 0.1,
  },
  vegetable: {
    type: "vegetable",
    category: "food",
    label: "Vegetable",
    stackSize: 50,
    baseValue: 1,
    weight: 0.3,
    flammability: 0,
    nutrition: 0.2,
  },
  meal_simple: {
    type: "meal_simple",
    category: "food",
    label: "Simple Meal",
    stackSize: 10,
    baseValue: 5,
    weight: 0.5,
    flammability: 0,
    nutrition: 0.8,
  },
  meal_fine: {
    type: "meal_fine",
    category: "food",
    label: "Fine Meal",
    stackSize: 10,
    baseValue: 10,
    weight: 0.5,
    flammability: 0,
    nutrition: 1.0,
  },

  // Tools
  pickaxe: {
    type: "pickaxe",
    category: "tool",
    label: "Pickaxe",
    stackSize: 1,
    baseValue: 20,
    weight: 2.0,
    flammability: 0,
    nutrition: 0,
  },
  axe: {
    type: "axe",
    category: "tool",
    label: "Axe",
    stackSize: 1,
    baseValue: 20,
    weight: 2.0,
    flammability: 0,
    nutrition: 0,
  },
  hammer: {
    type: "hammer",
    category: "tool",
    label: "Hammer",
    stackSize: 1,
    baseValue: 20,
    weight: 2.0,
    flammability: 0,
    nutrition: 0,
  },
};

export function getItemProperties(type: ItemType): ItemProperties {
  return ITEM_REGISTRY[type];
}
