import type { StructureProperties, StructureType } from "../types";

export const STRUCTURE_REGISTRY: Record<StructureType, StructureProperties> = {
  none: {
    type: "none",
    category: "decoration",
    blocksMovement: false,
    blocksVision: false,
    isInteractable: false,
    maxHealth: 0,
    flammability: 0,
  },
  wall_stone: {
    type: "wall_stone",
    category: "wall",
    blocksMovement: true,
    blocksVision: true,
    isInteractable: false,
    maxHealth: 500,
    flammability: 0,
  },
  wall_wood: {
    type: "wall_wood",
    category: "wall",
    blocksMovement: true,
    blocksVision: true,
    isInteractable: false,
    maxHealth: 200,
    flammability: 0.8,
  },
  wall_metal: {
    type: "wall_metal",
    category: "wall",
    blocksMovement: true,
    blocksVision: true,
    isInteractable: false,
    maxHealth: 800,
    flammability: 0,
  },
  wall_brick: {
    type: "wall_brick",
    category: "wall",
    blocksMovement: true,
    blocksVision: true,
    isInteractable: false,
    maxHealth: 400,
    flammability: 0,
  },
  door_wood: {
    type: "door_wood",
    category: "door",
    blocksMovement: false, // Can be opened
    blocksVision: true,
    isInteractable: true,
    maxHealth: 100,
    flammability: 0.9,
  },
  door_metal: {
    type: "door_metal",
    category: "door",
    blocksMovement: false,
    blocksVision: true,
    isInteractable: true,
    maxHealth: 300,
    flammability: 0,
  },
  door_auto: {
    type: "door_auto",
    category: "door",
    blocksMovement: false,
    blocksVision: false,
    isInteractable: true,
    maxHealth: 200,
    flammability: 0.1,
  },
  bed: {
    type: "bed",
    category: "furniture",
    blocksMovement: false,
    blocksVision: false,
    isInteractable: true,
    maxHealth: 100,
    flammability: 0.7,
  },
  chair: {
    type: "chair",
    category: "furniture",
    blocksMovement: false,
    blocksVision: false,
    isInteractable: true,
    maxHealth: 50,
    flammability: 0.7,
  },
  table: {
    type: "table",
    category: "furniture",
    blocksMovement: false,
    blocksVision: false,
    isInteractable: true,
    maxHealth: 80,
    flammability: 0.7,
  },
  workbench: {
    type: "workbench",
    category: "machine",
    blocksMovement: false,
    blocksVision: false,
    isInteractable: true,
    maxHealth: 150,
    flammability: 0.5,
  },
  chest: {
    type: "chest",
    category: "container",
    blocksMovement: false,
    blocksVision: false,
    isInteractable: true,
    maxHealth: 100,
    flammability: 0.6,
  },
  shelf: {
    type: "shelf",
    category: "container",
    blocksMovement: false,
    blocksVision: false,
    isInteractable: true,
    maxHealth: 60,
    flammability: 0.7,
  },
  stockpile_zone: {
    type: "stockpile_zone",
    category: "container",
    blocksMovement: false,
    blocksVision: false,
    isInteractable: false,
    maxHealth: Number.POSITIVE_INFINITY,
    flammability: 0,
  },
  tree_oak: {
    type: "tree_oak",
    category: "natural",
    blocksMovement: true,
    blocksVision: false,
    isInteractable: true, // Can be chopped
    maxHealth: 200,
    flammability: 0.6,
  },
  tree_pine: {
    type: "tree_pine",
    category: "natural",
    blocksMovement: true,
    blocksVision: false,
    isInteractable: true,
    maxHealth: 180,
    flammability: 0.7,
  },
  bush: {
    type: "bush",
    category: "natural",
    blocksMovement: false,
    blocksVision: false,
    isInteractable: true,
    maxHealth: 50,
    flammability: 0.8,
  },
  boulder: {
    type: "boulder",
    category: "natural",
    blocksMovement: true,
    blocksVision: false,
    isInteractable: true, // Can be mined
    maxHealth: 400,
    flammability: 0,
  },
};

export function getStructureProperties(
  type: StructureType,
): StructureProperties {
  return STRUCTURE_REGISTRY[type];
}
